### PR TITLE
Do not try to make regexes immutable

### LINKED ISSUE #722: [BUG] RegExp are proxified which breaks them
**Describe the bug**
Due to [this commit](https://github.com/node-config/node-config/commit/405e4082b6b015329d4300911bd6998482953ee7), regexes are now broken.

If your configuration contains a regex, you'll get a proxified regex which seems to be ok but it will crash as soon as you try to use it with an error: `TypeError: RegExp.prototype.source getter called on non-RegExp object`

**Expected behavior**
You can put regexes in your config files (in cjs or ts format) and use it in your code

### Please tell us about your environment:

 -  node-config version: 3.3.9
 -  node-version: 16.19.1
 
### Other information

A workaround is to enable `ALLOW_CONFIG_MUTATIONS` but it's not an acceptable solution

### PR DESCRIPTION
**Pull request by CGNonofr**
fixes #722

### CODE REVIEW

**Comment by markstos** [comment]
Please include a test suite test which fails before the change and passes afterwards.

**Comment by CGNonofr** [comment]
> Please include a test suite test which fails before the change and passes afterwards.

Just did in 9b9be2fceb7ccbf0c13865058dac13f97e40dd9d

**Comment by markstos** [comment]
Thank you. I see the code also affects Date objects as well. Please make sure that case is covered by a test as well.

**Comment by markstos** [comment]
Still waiting on the update for Dates.

**Comment by markstos** [comment]
Review the test suite and choose a good location.

**Comment by jeremy-daley-kr** [comment]
@CGNonofr and @markstos ... I believe this is the error I'm also experiencing, introduced in v3.3.8. Any thoughts how we can get this moving?

**Comment by markstos** [comment]
@jeremy-daley-kr I'll merge this once test coverage for the date case is added.

**Comment by jeremy-daley-kr** [comment]
> @jeremy-daley-kr I'll merge this once test coverage for the date case is added.

Ok. Lemme see if I can take over on that.

**Comment by jeremy-daley-kr** [comment]
@markstos Would you mind reviewing my PR to pick up where this one left off. Seemed simple enough to follow the current convention of tests:
https://github.com/node-config/node-config/pull/775

**Comment by jeremy-daley-kr** [comment]
Actually, the more I look at this, the more I wonder if `Config.get()` can just receive an additional param to bypass the mutability check. In some cases, it could mean just editing one line of code (where the `.get()` call exists, rather than changing multiple config files to use `{ key: raw(/some complex regexp/) }`

**Comment by markstos** [comment]
Closing in favor of #775

**Pull request closed without merging**
