### PR TITLE
fix: bypass Proxy for RegExp and Date objects

### PR DESCRIPTION
**Pull request by jeremy-daley-kr**
Picks up where https://github.com/node-config/node-config/pull/723 left it, and adds a test for `Date`.

Fixes:
* https://github.com/node-config/node-config/issues/722
* https://github.com/node-config/node-config/issues/694

### CODE REVIEW

**Comment by markstos** [comment]
Merged. Are there other issues or PRs that you'd like to see addressed in the next release?

**Comment by jeremy-daley-kr** [comment]
> Merged. Are there other issues or PRs that you'd like to see addressed in the next release?

No, sir. I think I'm good. Speaking of... Is there a cadence or process that new PRs tend to go through before next NPM publish?

**Comment by markstos** [comment]
@jeremy-daley-kr I'd like to get this out soon, but it looks like there's another parallel case with binary files to possibly address first, in #761

**Comment by jeremy-daley-kr** [comment]
> @jeremy-daley-kr I'd like to get this out soon, but it looks like there's another parallel case with binary files to possibly address first, in #761

I'll have to look into this when I get more time to do so. The `Proxy` thing is making a solution more "specific" than I'd prefer with a growing list of `instanceof` checks. If there's another way, I'd like to see if that exists.

I also started exploring adding a `get()` to the `Proxy` config, but don't have something yet that doesn't still require a chain of `|| instanceof`s:

```diff
+ value = new Proxy(obj, {
+   get(target, prop, receiver) {
+     if (target instanceof RegExp || target instanceof Date) {
+       const value = Reflect.get(target, prop, target);
+       if (typeof value === "function") {
+         return value.bind(target); // Bind methods to the target
+       }
+       return value; // Return property value as is
+     }
+     return Reflect.get(target, prop, receiver);
+   },
  set(target, prop, value) {
    throw new Error(`Cannot modify property "${prop}". Object is immutable.`);
  },
});
```

**Comment by daleyjem** [comment]
> Maybe we would better served by declaring the types that we /can/ make immutable rather than the types that we can't.

Can you take a look at this one?
https://github.com/node-config/node-config/pull/779

I feel better about it, because it keeps immutability, and doesn't require specific `instanceof` checks. From what I can tell, it fixes the `binary` issue as well (added test).

**Comment by Hassan222-ux** [comment]
||

**Comment by Hassan222-ux** [comment]
a get()

**Comment by Hassan222-ux** [comment]
Proxyالهدف

**Comment by Hassan222-ux** [comment]
value = new Proxy(obj, {
+   get(target, prop, receiver) {
+     if (target instanceof RegExp || target instanceof Date) {
+       const value = Reflect.get(target, prop, target);
+       if (typeof value === "function") {
+         return value.bind(target); // Bind methods to the target
+       }
+       return value; // Return property value as is
+     }
+     return Reflect.get(target, prop, receiver);
+   },
  set(target, prop, value) {
    throw new Error(`Cannot modify property "${prop}". Object is immutable.`);
  },
});

**Comment by markstos** [comment]
@Hassan222-ux What you are trying to communicate is not clear. Using a translation app to translate what you want to see into English if you need to.

**Pull request merged**
