### PR TITLE
Fixed property mutation. Throw an exception on such an attempt. Updat…

### PR DESCRIPTION
**Pull request by fgheorghe**
…ed tests to capture this exception.

### CODE REVIEW

**Comment by lorenwest** [comment]
This looks great.  I'm not as familiar with Proxy and Reflect as you are, so I can't give it a thorough review, but if it passes the tests and works on all versions tested by Travis it should be good.

**Comment by lorenwest** [comment]
I'll give it a day or two for others to review, then merge.

**Comment by fgheorghe** [comment]
Sounds good - thank you!

**Comment by markstos** [comment]
Apologies for the delayed merged.

It's helpful to explicitly throw errors when mutation attempts are made. This may need a major version bump as a behavior change, though.

**Comment by markstos** [comment]
@fgheorghe Could you check out the linked bug reports related to this change?

**Pull request merged**
