### PR TITLE
fix: lack of comments removal, invalid regexp

### PR DESCRIPTION
**Pull request by DeutscherDude**
This addresses issues mentioned in #715 
The issue mentioned in #704 will be investigated further

### CODE REVIEW

**Comment by DeutscherDude** [comment]
Hello @lorenwest,
I have amended the parsing of JSON to utilize JSON5 parser as per (this thread)[https://github.com/node-config/node-config/issues/715#issuecomment-1814967711].
Additionally, I removed the extraneous stripping of comments from CSON parser.
There are *some* changes introduced to stripComments, i.e. a new RegExp, which I amended, so that it does not use the [a-zA-z] honey pot.
Happy to introduce any further required changes :smile:

**Comment by timturnerwhcc** [comment]
@lorenwest @DeutscherDude There hasn't been much movement on this PR in a bit - it would be really helpful to have as my team is migrating to Node20.

I'm happy to give feedback on this PR or whatever else to help move it forward.

**Comment by jfberry** [comment]
We are also holding off a node-20+ migration because of this bug

**Comment by lorenwest** [comment]
This looks like a healthy change, and I wish it were as simple as approving and merging.  Unfortunately for health reasons I've been less than active in this project, and it seems that 2 test failures have crept into the master branch.

One of the problems was resolved in this branch, but there's another that needs further research before merging.  When did it start failing?  Is it a failure of the test or a failure of the baseline code? Does it only fail on one NodeJS version or many?  What was the original intent, and is it still relevant?  All of this takes time and energy to resolve, and my philosophy is to never merge into master with a single test failure, otherwise the effort everyone has put into these tests are diluted.

@markstos and I are the two authorized to merge into master and push a new release, and we've been doing it for 8-12 years, and neither of us is getting any younger.  Would anyone like to start taking the reigns for node-config going forward?  It's pretty stable, but does need TLC every now and then.

**Comment by jfberry** [comment]
I generally agree with your philosophy but it sounds like this pr doesn’t increase the failures that exist, in fact reduces them?
If so it’s a positive step forward. 
Besides what is a show stopper for people with particular config files upgrading to newer versions of node.

**Comment by DeutscherDude** [comment]
Happy to be of further aid in the future. I got pretty intimate with the code and feel comfortable with it :).
For now, I am rather entangled with finishing my engineering degree, but gimme a month 😊

**Comment by lorenwest** [comment]
Thanks for the offer @DeutscherDude .  For now I've disabled the failing test as I couldn't see how it could ever have worked.  Your branch was merged, a new release was created, and npm latest is now at v2.3.10

**Comment by Shayan1191** [comment]
It's very good

**Pull request merged**
