### PR TITLE
Added possibility to have custom configurable language files

### PR DESCRIPTION
**Pull request by maxiruani**
Feature related to #419. Any comment or suggestion is welcome. Thanks

### CODE REVIEW

**Comment by lorenwest** [comment]
Could you look into the reason this fails the Travis integration tests? It's usually because of early node version compatibility. There's a lot of people using node-config, and not everyone updates their node version to the latest.

**Comment by maxiruani** [comment]
@lorenwest I don't have any clue why the tests have failed. The Travis log doesn't say anything. I have tested locally with Node 0.12 with "npm test" and it works. Any ideas?

**Comment by lorenwest** [comment]
Check the [Details](https://travis-ci.org/lorenwest/node-config/builds/235738905?utm_source=github_status&utm_medium=notification) link on the failure slide, then drill down.

**Comment by maxiruani** [comment]
I already have. It says ["✓ OK » 186 honored "](https://travis-ci.org/lorenwest/node-config/jobs/235738908#L553)

An then for no reason it exited with code 1.

Sorry for bother you. Thanks in advance

**Comment by lorenwest** [comment]
Sometimes you have to run the tests in the same versions that Travis uses. [NVM](https://github.com/creationix/nvm) lets you easily install and switch node versions. It could be something as simple as a dropped newline at the end of a file, or an encoded character that earlier versions of node can't handle.

**Comment by markstos** [comment]
I'm closing this due to lack of interest and also because we've since merged a more flexible system of loading multiple NODE_ENV environments: 

https://github.com/node-config/node-config/wiki/Environment-Variables#node_env

It seems this could be used to load for example `NODE_ENV=production,EN` or `NODE_ENV=production,IT`.

**Pull request closed without merging**
